### ISSUE TITLE
Not calling didReceivePublicIPandPort

### ISSUE THREAD

**Issue by loretoparisi** [soulfly/STUN-iOS#2]
I cannot see the didReceivePublicIPandPort being called on iPhone6/iOS8.4/3G network.

**Comment by soulfly** [comment]
Hey
I didn't test it on iOS8, let me check

**Comment by soulfly** [comment]
ok, this is not related to iOS8

this is related to STUN server

I have replaced it with another one, just download this project again from GIT

This is my commit https://github.com/soulfly/STUN-iOS/commit/16dff41eddca0f0c7c85a02324a8bdfd262dd64b

**Comment by loretoparisi** [comment]
Ok thank you.
I have found a list of public stun server. Do you think you could rely on that one (like Google Stun Server) or moving to a new stun server if someone does not echoes messages back?

https://gist.github.com/zziuni/3741933
